package au.com.threesixty.cabdispatch.domain

/**
 * Single source of truth for "is this tablet unpaired" — i.e. has it ever completed
 * `POST /v1/fleet/devices/register` and gotten back a real [DeviceCommandState.deviceId].
 *
 * ### Why this exists (2026-09-06 defect pass)
 * Before this class, three call sites each re-derived the same fact by comparing
 * [SessionHolder.deviceId] (or the mirrored [DeviceCommandState.deviceId]) against `null` inline:
 * [au.com.threesixty.cabdispatch.ui.overlays.DeviceUnpairedBanner] (should the app-wide banner
 * show), [au.com.threesixty.cabdispatch.ui.screens.login.LoginVehicleBindViewModel.bindVehicle]
 * (should the onboarding advisory fire), and S6's own "tap to pair" tile
 * ([au.com.threesixty.cabdispatch.ui.screens.settings.SettingsViewModel]). Centralising it here
 * means the definition of "unpaired" can only ever drift in one place, and — the actual point of
 * this class — it is unit-testable on the plain JVM with no `Application`/Compose/Robolectric
 * involved, unlike the `AndroidViewModel`s that consume it.
 *
 * ### Found live driving a real onboarding end to end (2026-09-06)
 * A driver can complete the entire onboarding — permissions, disclaimer, sign-in, "Bind to
 * vehicle" (either its QR-scan or manual-rego path — **both** call
 * [au.com.threesixty.cabdispatch.ui.screens.login.LoginVehicleBindViewModel.bindVehicle], which
 * only resolves a rego to a fleet-vehicle UUID via `GET /v1/fleet/vehicles`; neither path calls
 * `POST /v1/fleet/devices/register`), pre-shift inspection, shift start, and run fares — while
 * [SessionHolder.deviceId] stays `null` the entire time. Confirmed live: 460 position-heartbeat
 * publishes, 0 device-command-heartbeat polls (that class hard-gates on this exact value — see
 * [DeviceCommandHeartbeat]'s "Gated on *paired*" section), so remote kiosk-lock/locate/force-update
 * sat at "Pending" forever and the dashboard's device row went stale — and nothing in the
 * onboarding flow ever told the driver or an operator standing next to them.
 *
 * ### Why the rego path cannot self-register, confirmed against the backend contract
 * `POST /v1/fleet/devices/register` (`shared/openapi.json` `DeviceRegisterRequest`) requires a
 * `pairing_code` that only `POST /v1/fleet/vehicles/{id}/pairing-code` can mint, and that endpoint
 * is `_require_admin` server-side (`backend/app/api/v1/fleet.py`, `require_role("owner", "admin")`)
 * — a driver's own session token can never call it. So there is no data this app could honestly
 * synthesize to make the rego-bind path register a device; a real pairing code, generated by an
 * operator and entered once through Settings ▸ Pair Meter (or scanned there), is the only real
 * path. This class exists to make that gap visible rather than to paper over it.
 */
object DevicePairingStatus {
    /** `true` until this tablet's next real [au.com.threesixty.cabdispatch.data.remote.ApiService.registerDevice]
     * call succeeds — see this object's class doc. Blank is treated the same as `null` defensively
     * (never actually produced by [DevicePairingStore.saveDeviceId]/[SessionHolder], which both only
     * ever write a real server-assigned id), so a stray empty string can never be mistaken for a
     * paired tablet. */
    fun isUnpaired(deviceId: String?): Boolean = deviceId.isNullOrBlank()
}
