"""D10 (security settings): MFA recovery codes.

Ten single-use codes generated by `app.core.security.generate_recovery_codes`
(stdlib `secrets` CSPRNG) at `POST /v1/auth/mfa/recovery-codes/generate`,
shown to the user exactly once in that response, and never seen again —
only the bcrypt hash of each (via `app.core.security.hash_recovery_code`,
the SAME hashing call `hash_password` uses; this is not a second scheme)
is ever persisted here, and never logged.

Each row is single-use: `consumed_at` is set the moment a code is accepted
by POST /v1/auth/mfa/login as an alternative to a TOTP code, and a consumed
row is never matched again (see app/api/v1/auth.py::mfa_login).
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base, TimestampMixin


class RecoveryCode(Base, TimestampMixin):
    __tablename__ = "recovery_codes"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id: Mapped[str] = mapped_column(String(36), ForeignKey("users.id"), nullable=False, index=True)
    code_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    consumed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


__all__ = ["RecoveryCode"]
