"""duress camera snapshots

Revision ID: 0201776e9446
Revises: c5f5e2009707
Create Date: 2026-08-27 19:17:22.299581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0201776e9446'
down_revision: Union[str, Sequence[str], None] = 'c5f5e2009707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duress_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('relative_path', sa.String(length=255), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duress_snapshots_event_id'), 'duress_snapshots', ['event_id'], unique=False)
    op.create_index(op.f('ix_duress_snapshots_tenant_id'), 'duress_snapshots', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_duress_snapshots_tenant_id'), table_name='duress_snapshots')
    op.drop_index(op.f('ix_duress_snapshots_event_id'), table_name='duress_snapshots')
    op.drop_table('duress_snapshots')
    # ### end Alembic commands ###
