"""shift break tracking

Revision ID: 0db130c8824f
Revises: 0201776e9446
Create Date: 2026-08-28 01:53:50.745052

Two nullable-extra-column additions to the existing shifts table, following
the exact same precedent as 30d61efb3583 (plotted_zone_id/plotted_at) --
break_started_at (nullable DateTime) and break_taken (non-nullable Boolean).
break_taken needs a server_default so this ALTER TABLE does not fail against
existing seeded rows on Postgres (SQLite silently accepts a NOT NULL column
add with no default; Postgres does not) -- same rationale as
75e755024e78 (mfa_enabled). Hand-adjusted after autogenerate to add
server_default=sa.false(), NOT sa.text("0") -- this codebase has a
documented real Postgres-vs-SQLite bug precedent where an integer-literal
Boolean server_default crashes on Postgres even though SQLite accepts it;
sa.false() is the portable form already used by 75e755024e78,
6b8e6598e086, and a7f2b8c4d1e6.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db130c8824f'
down_revision: Union[str, Sequence[str], None] = '0201776e9446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('break_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        'shifts',
        sa.Column('break_taken', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'break_taken')
    op.drop_column('shifts', 'break_started_at')
    # ### end Alembic commands ###
