"""phase 0: tenant settings, user identity columns, vehicle onboarding columns

Revision ID: 29a526968128
Revises: 0db130c8824f
Create Date: 2026-08-28 17:14:04.635093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a526968128'
down_revision: Union[str, Sequence[str], None] = '0db130c8824f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('fatigue_shift_duration_limit_hours', sa.Numeric(precision=4, scale=1), server_default='12.0', nullable=False),
    sa.Column('compliance_expiry_warning_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('duress_escalation_call_phone', sa.String(length=32), nullable=True),
    sa.Column('duress_call_from_number', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_settings_tenant_id'), 'tenant_settings', ['tenant_id'], unique=True)
    op.add_column('users', sa.Column('driver_authority_no', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('criminal_history_last_checked_at', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('criminal_history_next_due_at', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('suitability_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('vehicles', sa.Column('taxi_licence_no', sa.String(length=50), nullable=True))
    op.add_column('vehicles', sa.Column('licence_expiry', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('inspection_expiry', sa.Date(), nullable=True))
    op.add_column('vehicles', sa.Column('operating_area', sa.String(length=20), server_default='country', nullable=False))
    op.add_column('vehicles', sa.Column('make', sa.String(length=50), nullable=True))
    op.add_column('vehicles', sa.Column('model', sa.String(length=50), nullable=True))
    op.add_column('vehicles', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('wav_capacity', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('odometer_km', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'odometer_km')
    op.drop_column('vehicles', 'wav_capacity')
    op.drop_column('vehicles', 'year')
    op.drop_column('vehicles', 'model')
    op.drop_column('vehicles', 'make')
    op.drop_column('vehicles', 'operating_area')
    op.drop_column('vehicles', 'inspection_expiry')
    op.drop_column('vehicles', 'licence_expiry')
    op.drop_column('vehicles', 'taxi_licence_no')
    op.drop_column('users', 'suitability_status')
    op.drop_column('users', 'criminal_history_next_due_at')
    op.drop_column('users', 'criminal_history_last_checked_at')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'driver_authority_no')
    op.drop_index(op.f('ix_tenant_settings_tenant_id'), table_name='tenant_settings')
    op.drop_table('tenant_settings')
    # ### end Alembic commands ###
