"""blueprint phase 1 features

Revision ID: 6b8e6598e086
Revises: 75e755024e78
Create Date: 2026-08-02 16:25:32.130132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8e6598e086'
down_revision: Union[str, Sequence[str], None] = '75e755024e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fatigue_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('shift_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fatigue_alerts_driver_id'), 'fatigue_alerts', ['driver_id'], unique=False)
    op.create_index(op.f('ix_fatigue_alerts_kind'), 'fatigue_alerts', ['kind'], unique=False)
    op.create_index(op.f('ix_fatigue_alerts_shift_id'), 'fatigue_alerts', ['shift_id'], unique=False)
    op.create_index(op.f('ix_fatigue_alerts_tenant_id'), 'fatigue_alerts', ['tenant_id'], unique=False)
        # sa.false() (not sa.text('0')) -- '0' is a SQLite-only boolean literal;
    # Postgres rejects an integer-typed default on a BOOLEAN column outright
    # (DatatypeMismatchError), which this add_column never hit until it first
    # ran against real Postgres.
    op.add_column('devices', sa.Column('locate_requested', sa.Boolean(), server_default=sa.false(), nullable=False))
        # sa.false() (not sa.text('0')) -- '0' is a SQLite-only boolean literal;
    # Postgres rejects an integer-typed default on a BOOLEAN column outright
    # (DatatypeMismatchError), which this add_column never hit until it first
    # ran against real Postgres.
    op.add_column('devices', sa.Column('reboot_requested', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'reboot_requested')
    op.drop_column('devices', 'locate_requested')
    op.drop_index(op.f('ix_fatigue_alerts_tenant_id'), table_name='fatigue_alerts')
    op.drop_index(op.f('ix_fatigue_alerts_shift_id'), table_name='fatigue_alerts')
    op.drop_index(op.f('ix_fatigue_alerts_kind'), table_name='fatigue_alerts')
    op.drop_index(op.f('ix_fatigue_alerts_driver_id'), table_name='fatigue_alerts')
    op.drop_table('fatigue_alerts')
    # ### end Alembic commands ###
