"""phase 1: user invites, mfa recovery codes, tenant status

Revision ID: 713ba14b6265
Revises: 29a526968128
Create Date: 2026-08-28 19:20:35.722786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '713ba14b6265'
down_revision: Union[str, Sequence[str], None] = '29a526968128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa_recovery_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfa_recovery_codes_code_hash'), 'mfa_recovery_codes', ['code_hash'], unique=True)
    op.create_index(op.f('ix_mfa_recovery_codes_user_id'), 'mfa_recovery_codes', ['user_id'], unique=False)
    op.create_table('user_invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_invites_tenant_id'), 'user_invites', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_invites_token_hash'), 'user_invites', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_invites_user_id'), 'user_invites', ['user_id'], unique=False)
    op.add_column('tenants', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'status')
    op.drop_index(op.f('ix_user_invites_user_id'), table_name='user_invites')
    op.drop_index(op.f('ix_user_invites_token_hash'), table_name='user_invites')
    op.drop_index(op.f('ix_user_invites_tenant_id'), table_name='user_invites')
    op.drop_table('user_invites')
    op.drop_index(op.f('ix_mfa_recovery_codes_user_id'), table_name='mfa_recovery_codes')
    op.drop_index(op.f('ix_mfa_recovery_codes_code_hash'), table_name='mfa_recovery_codes')
    op.drop_table('mfa_recovery_codes')
    # ### end Alembic commands ###
