"""jobs and messages

Revision ID: 7b7a31a35ebd
Revises: f622cc063e66
Create Date: 2026-08-01 17:28:45.988749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7a31a35ebd'
down_revision: Union[str, Sequence[str], None] = 'f622cc063e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_availability',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'driver_id', name='uq_driver_availability_tenant_driver')
    )
    op.create_index(op.f('ix_driver_availability_driver_id'), 'driver_availability', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_availability_tenant_id'), 'driver_availability', ['tenant_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lng', sa.Float(), nullable=False),
    sa.Column('origin_address', sa.String(length=500), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lng', sa.Float(), nullable=False),
    sa.Column('dest_address', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('fare_estimate_low', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fare_estimate_high', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('accepted_by_driver_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_accepted_by_driver_id'), 'jobs', ['accepted_by_driver_id'], unique=False)
    op.create_index(op.f('ix_jobs_created_by_user_id'), 'jobs', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('sender_type', sa.String(length=10), nullable=False),
    sa.Column('sender_user_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_driver_id'), 'messages', ['driver_id'], unique=False)
    op.create_index(op.f('ix_messages_sent_at'), 'messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_table('job_offers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('offered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_offers_driver_id'), 'job_offers', ['driver_id'], unique=False)
    op.create_index(op.f('ix_job_offers_job_id'), 'job_offers', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_offers_status'), 'job_offers', ['status'], unique=False)
    op.create_index(op.f('ix_job_offers_tenant_id'), 'job_offers', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_offers_tenant_id'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_status'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_job_id'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_driver_id'), table_name='job_offers')
    op.drop_table('job_offers')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sent_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_driver_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_by_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_accepted_by_driver_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_driver_availability_tenant_id'), table_name='driver_availability')
    op.drop_index(op.f('ix_driver_availability_driver_id'), table_name='driver_availability')
    op.drop_table('driver_availability')
    # ### end Alembic commands ###
