"""phase 3: shift handover, D-1 partial unique indexes, odometer, end-of-shift inspection

Revision ID: 86ac23973f87
Revises: 8f7720c0986f
Create Date: 2026-08-29 18:10:53.877328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ac23973f87'
down_revision: Union[str, Sequence[str], None] = '8f7720c0986f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_handovers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outgoing_shift_id', sa.String(length=36), nullable=False),
    sa.Column('incoming_shift_id', sa.String(length=36), nullable=False),
    sa.Column('handed_over_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('handed_over_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('odometer_end', sa.Integer(), nullable=True),
    sa.Column('fuel_level', sa.Integer(), nullable=True),
    sa.Column('cleanliness_notes', sa.Text(), nullable=True),
    sa.Column('damage_notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['handed_over_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incoming_shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['outgoing_shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_handovers_handed_over_by_user_id'), 'shift_handovers', ['handed_over_by_user_id'], unique=False)
    op.create_index(op.f('ix_shift_handovers_incoming_shift_id'), 'shift_handovers', ['incoming_shift_id'], unique=False)
    op.create_index(op.f('ix_shift_handovers_outgoing_shift_id'), 'shift_handovers', ['outgoing_shift_id'], unique=False)
    op.create_index(op.f('ix_shift_handovers_tenant_id'), 'shift_handovers', ['tenant_id'], unique=False)
    op.add_column('devices', sa.Column('device_secret_hash', sa.String(length=64), nullable=True))
    op.add_column('shifts', sa.Column('odometer_start', sa.Integer(), nullable=True))
    op.add_column('shifts', sa.Column('odometer_end', sa.Integer(), nullable=True))
    op.add_column('shifts', sa.Column('end_inspection_json', sa.JSON(), nullable=True))
    op.create_index('uq_shifts_one_open_per_driver', 'shifts', ['tenant_id', 'driver_id'], unique=True, postgresql_where=sa.text('end_at IS NULL'), sqlite_where=sa.text('end_at IS NULL'))
    op.create_index('uq_shifts_one_open_per_vehicle', 'shifts', ['tenant_id', 'vehicle_id'], unique=True, postgresql_where=sa.text('end_at IS NULL'), sqlite_where=sa.text('end_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_shifts_one_open_per_vehicle', table_name='shifts', postgresql_where=sa.text('end_at IS NULL'), sqlite_where=sa.text('end_at IS NULL'))
    op.drop_index('uq_shifts_one_open_per_driver', table_name='shifts', postgresql_where=sa.text('end_at IS NULL'), sqlite_where=sa.text('end_at IS NULL'))
    op.drop_column('shifts', 'end_inspection_json')
    op.drop_column('shifts', 'odometer_end')
    op.drop_column('shifts', 'odometer_start')
    op.drop_column('devices', 'device_secret_hash')
    op.drop_index(op.f('ix_shift_handovers_tenant_id'), table_name='shift_handovers')
    op.drop_index(op.f('ix_shift_handovers_outgoing_shift_id'), table_name='shift_handovers')
    op.drop_index(op.f('ix_shift_handovers_incoming_shift_id'), table_name='shift_handovers')
    op.drop_index(op.f('ix_shift_handovers_handed_over_by_user_id'), table_name='shift_handovers')
    op.drop_table('shift_handovers')
    # ### end Alembic commands ###
