"""phase 2: device assignment, vehicle assignment roster, drop meter_device_id

Revision ID: 8f7720c0986f
Revises: 713ba14b6265
Create Date: 2026-08-28 21:12:05.927081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7720c0986f'
down_revision: Union[str, Sequence[str], None] = '713ba14b6265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('authorised_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('authorised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['authorised_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_assignments_driver_id'), 'vehicle_assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_tenant_id'), 'vehicle_assignments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_vehicle_id'), 'vehicle_assignments', ['vehicle_id'], unique=False)
    op.create_index('uq_vehicle_assignments_active_driver_vehicle', 'vehicle_assignments', ['tenant_id', 'vehicle_id', 'driver_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'), sqlite_where=sa.text('revoked_at IS NULL'))
    op.create_table('device_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('bound_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bound_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('pairing_code_id', sa.String(length=36), nullable=True),
    sa.Column('unbound_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['bound_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['pairing_code_id'], ['device_pairing_codes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_assignments_device_id'), 'device_assignments', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_assignments_tenant_id'), 'device_assignments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_device_assignments_vehicle_id'), 'device_assignments', ['vehicle_id'], unique=False)
    op.create_index('uq_device_assignments_one_active_per_device', 'device_assignments', ['tenant_id', 'device_id'], unique=True, postgresql_where=sa.text('unbound_at IS NULL'), sqlite_where=sa.text('unbound_at IS NULL'))
    op.create_index('uq_device_assignments_one_active_per_vehicle', 'device_assignments', ['tenant_id', 'vehicle_id'], unique=True, postgresql_where=sa.text('unbound_at IS NULL'), sqlite_where=sa.text('unbound_at IS NULL'))
    op.drop_column('vehicles', 'meter_device_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('meter_device_id', sa.VARCHAR(length=100), nullable=True))
    op.drop_index('uq_device_assignments_one_active_per_vehicle', table_name='device_assignments', postgresql_where=sa.text('unbound_at IS NULL'), sqlite_where=sa.text('unbound_at IS NULL'))
    op.drop_index('uq_device_assignments_one_active_per_device', table_name='device_assignments', postgresql_where=sa.text('unbound_at IS NULL'), sqlite_where=sa.text('unbound_at IS NULL'))
    op.drop_index(op.f('ix_device_assignments_vehicle_id'), table_name='device_assignments')
    op.drop_index(op.f('ix_device_assignments_tenant_id'), table_name='device_assignments')
    op.drop_index(op.f('ix_device_assignments_device_id'), table_name='device_assignments')
    op.drop_table('device_assignments')
    op.drop_index('uq_vehicle_assignments_active_driver_vehicle', table_name='vehicle_assignments', postgresql_where=sa.text('revoked_at IS NULL'), sqlite_where=sa.text('revoked_at IS NULL'))
    op.drop_index(op.f('ix_vehicle_assignments_vehicle_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_tenant_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_driver_id'), table_name='vehicle_assignments')
    op.drop_table('vehicle_assignments')
    # ### end Alembic commands ###
