"""job type, distance, eta for dispatch cards

Revision ID: 9a9364f2c706
Revises: 86ac23973f87
Create Date: 2026-08-29 19:12:34.562630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9364f2c706'
down_revision: Union[str, Sequence[str], None] = '86ac23973f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_type', sa.String(length=12), nullable=False, server_default='booked'))
    op.add_column('jobs', sa.Column('distance_km', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('eta_min', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'eta_min')
    op.drop_column('jobs', 'distance_km')
    op.drop_column('jobs', 'job_type')
    # ### end Alembic commands ###
