"""trip.simulated: mark trips driven on fabricated GPS

Revision ID: c41d7be90a52
Revises: 7060b390bade
Create Date: 2026-09-07 00:00:00.000000

Adds `trips.simulated` — see `app.models.trips.Trip.simulated` for the full
reasoning. In short: the Android meter now ships a GPS simulator for testing
the fare engine and toll detection without driving, and a trip driven on
fabricated fixes produces a `gps_trace` that replays cleanly through
`app.services.trips.recompute_from_trace` and passes the fare-variance check
exactly like a genuine fare. The server cannot tell the difference on its own,
so the device that fabricated the fixes sends this flag, and it is what keeps a
test drive out of an operator's real revenue and out of the compliance evidence
for a fare-regulated meter.

Purely additive and safe to apply to a live database: NOT NULL with a
`server_default` of false, so every existing row becomes `simulated = false`
(correct — they were all real) without a table rewrite of user-visible data.

Hand-written rather than autogenerated: `alembic revision --autogenerate`
requires a database at head, and this project's local dev database is SQLite,
whose dialect cannot apply an earlier migration in the chain ("No support for
ALTER of constraints in SQLite dialect"). A single additive column does not
need autogenerate.
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "c41d7be90a52"
down_revision = "7060b390bade"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "trips",
        sa.Column("simulated", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # Indexed because the entire purpose of the column is filtering simulated
    # trips out of (or into) reporting -- an unindexed flag on the trips table
    # would mean a sequential scan for every such query.
    op.create_index(op.f("ix_trips_simulated"), "trips", ["simulated"])


def downgrade() -> None:
    op.drop_index(op.f("ix_trips_simulated"), table_name="trips")
    op.drop_column("trips", "simulated")
