"""user driver code

Revision ID: d613d986df6e
Revises: d4a7b1e39c5f
Create Date: 2026-08-03 10:36:00.326020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd613d986df6e'
down_revision: Union[str, Sequence[str], None] = 'd4a7b1e39c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Real driver-facing login (POST /v1/auth/driver-login), replacing the
    # placeholder driverId->email/pin->password mapping documented in the
    # Android app's DriverAuthRepository.kt. Nullable, no server_default
    # needed — every existing user simply has no driver_code yet (only newly
    # created role="driver" accounts get one going forward, see
    # app/api/v1/users.py). Globally unique like users.email (see
    # app/services/user.py::assert_driver_code_available for why it can't be
    # tenant-scoped).
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('driver_code', sa.String(length=6), nullable=True))
    op.create_index(op.f('ix_users_driver_code'), 'users', ['driver_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_driver_code'), table_name='users')
    op.drop_column('users', 'driver_code')
    # ### end Alembic commands ###
