"""initial schema

Revision ID: f622cc063e66
Revises: efd8acc1383a
Create Date: 2026-07-31 09:30:30.825571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f622cc063e66'
down_revision: Union[str, Sequence[str], None] = 'efd8acc1383a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duress_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('trigger', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gps_stream_ref', sa.String(length=255), nullable=False),
    sa.Column('audio_ref', sa.String(length=255), nullable=True),
    sa.Column('escalation_log_json', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duress_events_driver_id'), 'duress_events', ['driver_id'], unique=False)
    op.create_index(op.f('ix_duress_events_status'), 'duress_events', ['status'], unique=False)
    op.create_index(op.f('ix_duress_events_tenant_id'), 'duress_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_duress_events_vehicle_id'), 'duress_events', ['vehicle_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_id', sa.String(length=36), nullable=False),
    sa.Column('stripe_pi_id', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('surcharge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_given', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('docket_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_stripe_pi_id'), 'payments', ['stripe_pi_id'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_payments_trip_id'), 'payments', ['trip_id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspection_json', sa.JSON(), nullable=True),
    sa.Column('trips_count', sa.Integer(), nullable=False),
    sa.Column('km_total', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('cash_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('card_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('psl_owed', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reconciled', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_driver_id'), 'shifts', ['driver_id'], unique=False)
    op.create_index(op.f('ix_shifts_tenant_id'), 'shifts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_shifts_vehicle_id'), 'shifts', ['vehicle_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price_aud', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_vehicle_id'), 'subscriptions', ['vehicle_id'], unique=False)
    op.create_table('tariffs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booked', sa.Boolean(), nullable=False),
    sa.Column('flag_fall', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('peak_charge', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('dist_rate_1', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('dist_rate_2', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('night_rate_1', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('night_rate_2', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('holiday_rate_1', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('holiday_rate_2', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('waiting_rate_per_min', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('dist_km_threshold', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('speed_threshold_kmh', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('maxi_multiplier', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('multi_hire_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('psl_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('surcharge_pct_cap', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_region'), 'tariffs', ['region'], unique=False)
    op.create_index(op.f('ix_tariffs_tenant_id'), 'tariffs', ['tenant_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('shift_id', sa.String(length=36), nullable=True),
    sa.Column('tariff_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('time_class', sa.String(length=10), nullable=False),
    sa.Column('is_peak', sa.Boolean(), nullable=False),
    sa.Column('maxi', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=False),
    sa.Column('start_lng', sa.Float(), nullable=False),
    sa.Column('end_lat', sa.Float(), nullable=True),
    sa.Column('end_lng', sa.Float(), nullable=True),
    sa.Column('last_lat', sa.Float(), nullable=True),
    sa.Column('last_lng', sa.Float(), nullable=True),
    sa.Column('last_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distance_m', sa.Integer(), nullable=False),
    sa.Column('moving_s', sa.Integer(), nullable=False),
    sa.Column('waiting_s', sa.Integer(), nullable=False),
    sa.Column('flag_fall', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dist_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('wait_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('peak_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tolls', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('psl', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('extras', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('surcharge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst_component', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('gps_trace_ref', sa.Text(), nullable=True),
    sa.Column('max_fare_check_passed', sa.Boolean(), nullable=False),
    sa.Column('variance_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('receipt_ref', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'client_uuid', name='uq_trips_tenant_client_uuid')
    )
    op.create_index(op.f('ix_trips_client_uuid'), 'trips', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trips_shift_id'), 'trips', ['shift_id'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_tariff_id'), 'trips', ['tariff_id'], unique=False)
    op.create_index(op.f('ix_trips_tenant_id'), 'trips', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rego', sa.String(length=20), nullable=False),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('vehicle_class', sa.String(length=20), nullable=False),
    sa.Column('camera_serial', sa.String(length=100), nullable=True),
    sa.Column('tracking_device_id', sa.String(length=100), nullable=True),
    sa.Column('meter_device_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'rego', name='uq_vehicles_tenant_rego')
    )
    op.create_index(op.f('ix_vehicles_rego'), 'vehicles', ['rego'], unique=False)
    op.create_index(op.f('ix_vehicles_tenant_id'), 'vehicles', ['tenant_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('compliance_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_documents_doc_type'), 'compliance_documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_compliance_documents_tenant_id'), 'compliance_documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_compliance_documents_uploaded_by'), 'compliance_documents', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_compliance_documents_vehicle_id'), 'compliance_documents', ['vehicle_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('android_id', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('app_version', sa.String(length=30), nullable=True),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('kiosk_locked', sa.Boolean(), nullable=False),
    sa.Column('force_update_pending', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('network', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'android_id', name='uq_devices_tenant_android_id')
    )
    op.create_index(op.f('ix_devices_android_id'), 'devices', ['android_id'], unique=False)
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_devices_vehicle_id'), 'devices', ['vehicle_id'], unique=False)
    op.create_table('psl_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('trips_count', sa.Integer(), nullable=False),
    sa.Column('amount_owed', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_collected', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'driver_id', 'period', name='uq_psl_ledger_tenant_driver_period')
    )
    op.create_index(op.f('ix_psl_ledger_driver_id'), 'psl_ledger', ['driver_id'], unique=False)
    op.create_index(op.f('ix_psl_ledger_period'), 'psl_ledger', ['period'], unique=False)
    op.create_index(op.f('ix_psl_ledger_tenant_id'), 'psl_ledger', ['tenant_id'], unique=False)
    op.create_table('psl_topups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('stripe_charge_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psl_topups_driver_id'), 'psl_topups', ['driver_id'], unique=False)
    op.create_index(op.f('ix_psl_topups_period'), 'psl_topups', ['period'], unique=False)
    op.create_index(op.f('ix_psl_topups_tenant_id'), 'psl_topups', ['tenant_id'], unique=False)
    op.create_table('tariff_change_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tariff_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_change_log_tariff_id'), 'tariff_change_log', ['tariff_id'], unique=False)
    op.create_index(op.f('ix_tariff_change_log_tenant_id'), 'tariff_change_log', ['tenant_id'], unique=False)
    op.create_table('tariff_extras',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tariff_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_extras_tariff_id'), 'tariff_extras', ['tariff_id'], unique=False)
    op.create_index(op.f('ix_tariff_extras_tenant_id'), 'tariff_extras', ['tenant_id'], unique=False)
    op.create_table('device_pairing_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_device_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['used_by_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_pairing_codes_code'), 'device_pairing_codes', ['code'], unique=False)
    op.create_index(op.f('ix_device_pairing_codes_tenant_id'), 'device_pairing_codes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_device_pairing_codes_vehicle_id'), 'device_pairing_codes', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_pairing_codes_vehicle_id'), table_name='device_pairing_codes')
    op.drop_index(op.f('ix_device_pairing_codes_tenant_id'), table_name='device_pairing_codes')
    op.drop_index(op.f('ix_device_pairing_codes_code'), table_name='device_pairing_codes')
    op.drop_table('device_pairing_codes')
    op.drop_index(op.f('ix_tariff_extras_tenant_id'), table_name='tariff_extras')
    op.drop_index(op.f('ix_tariff_extras_tariff_id'), table_name='tariff_extras')
    op.drop_table('tariff_extras')
    op.drop_index(op.f('ix_tariff_change_log_tenant_id'), table_name='tariff_change_log')
    op.drop_index(op.f('ix_tariff_change_log_tariff_id'), table_name='tariff_change_log')
    op.drop_table('tariff_change_log')
    op.drop_index(op.f('ix_psl_topups_tenant_id'), table_name='psl_topups')
    op.drop_index(op.f('ix_psl_topups_period'), table_name='psl_topups')
    op.drop_index(op.f('ix_psl_topups_driver_id'), table_name='psl_topups')
    op.drop_table('psl_topups')
    op.drop_index(op.f('ix_psl_ledger_tenant_id'), table_name='psl_ledger')
    op.drop_index(op.f('ix_psl_ledger_period'), table_name='psl_ledger')
    op.drop_index(op.f('ix_psl_ledger_driver_id'), table_name='psl_ledger')
    op.drop_table('psl_ledger')
    op.drop_index(op.f('ix_devices_vehicle_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_android_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_compliance_documents_vehicle_id'), table_name='compliance_documents')
    op.drop_index(op.f('ix_compliance_documents_uploaded_by'), table_name='compliance_documents')
    op.drop_index(op.f('ix_compliance_documents_tenant_id'), table_name='compliance_documents')
    op.drop_index(op.f('ix_compliance_documents_doc_type'), table_name='compliance_documents')
    op.drop_table('compliance_documents')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_vehicles_tenant_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_rego'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_trips_vehicle_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_tenant_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_tariff_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_shift_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_client_uuid'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_tariffs_tenant_id'), table_name='tariffs')
    op.drop_index(op.f('ix_tariffs_region'), table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_index(op.f('ix_subscriptions_vehicle_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_shifts_vehicle_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_tenant_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_driver_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_payments_trip_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_stripe_pi_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_duress_events_vehicle_id'), table_name='duress_events')
    op.drop_index(op.f('ix_duress_events_tenant_id'), table_name='duress_events')
    op.drop_index(op.f('ix_duress_events_status'), table_name='duress_events')
    op.drop_index(op.f('ix_duress_events_driver_id'), table_name='duress_events')
    op.drop_table('duress_events')
    # ### end Alembic commands ###
