package au.com.threesixty.cabdispatch.data.local.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index

/**
 * One GPS/speed fix appended to an open trip's route trace — the append-only replacement for the
 * old `TripEntity.gpsTraceJson` "decode the whole trip, append one point, re-encode the whole
 * trip, rewrite the whole row" write on every tick (G8, architecture audit 2026-09-08 §2.1 /
 * the 2026-09-12 optimisation plan's W4 §3: *"a 2-hour hire at 1 Hz rewrites a ~7,000-point JSON
 * string 7,000 times — measurable jank and battery on the tablet, and a Room write amplification
 * problem"*).
 *
 * Written by [au.com.threesixty.cabdispatch.data.repository.TripRepository.tick] in small batches
 * (every 5s or 10 points, whichever comes first — see that method's `bufferTracePoints` doc), each
 * batch a plain `INSERT` of new rows only — no read-decode-append-reencode-write of anything that
 * grows with the trip's length, which is what makes the total write cost O(n) over an n-tick trip
 * instead of the old O(n^2).
 *
 * [TripEntity.gpsTraceJson] itself is NOT removed: it is still what
 * `TripSyncItemDto.gpsTrace`/the server's `recompute_from_trace` read, and still what
 * [au.com.threesixty.cabdispatch.data.repository.TripRepository.observeActiveTripGpsTrace]'s
 * on-screen route-polyline reader ultimately serves from during a live trip — but it is now
 * materialised from this table exactly once, at [au.com.threesixty.cabdispatch.data.repository.TripRepository.closeTrip]
 * time, rather than kept live-updated on every tick. This table's own rows are deleted once a
 * trip's sync to the server is confirmed (`markSynced`) — see that method's doc — so it never
 * grows to hold more than one still-unsynced trip's worth of points on-device.
 *
 * Keyed by `(tripClientUuid, seq)` rather than a Room-autogenerated rowid so ordering is explicit
 * and stable across a process restart mid-trip: [seq] is assigned by
 * [au.com.threesixty.cabdispatch.data.repository.TripRepository] itself (continuing from
 * `MAX(seq)` already on disk for that trip, not from an in-memory counter that a crash would
 * reset to zero and start colliding with).
 */
@Entity(
    tableName = "trip_trace_points",
    primaryKeys = ["tripClientUuid", "seq"],
    indices = [Index("tripClientUuid")],
    foreignKeys = [
        ForeignKey(
            entity = TripEntity::class,
            parentColumns = ["clientUuid"],
            childColumns = ["tripClientUuid"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
)
data class TripTracePointEntity(
    val tripClientUuid: String,
    /** Monotonically increasing per trip, 0-based, assigned at flush time — see class doc. Never
     * reused within a trip, so `ORDER BY seq` always reproduces the exact order points were
     * driven in, matching what the old `gpsTraceJson` list order already guaranteed. */
    val seq: Int,
    val lat: Double,
    val lng: Double,
    val speedKmh: Double,
    /** ISO-8601 timestamp, same field as [au.com.threesixty.cabdispatch.data.remote.TelemetryPointDto.ts]
     * — carried straight through, never re-derived. */
    val ts: String,
)
