package au.com.threesixty.cabdispatch.data.local

import androidx.room.Room
import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.core.app.ApplicationProvider
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * Executes the real `8 -> 9 -> 10 -> 11 -> 12` [AppDatabase] migration chain against a real
 * SQLite file, via Room's own [MigrationTestHelper], and validates the result against the
 * schema Room's annotation processor compiles from the CURRENT entity classes. This is A9's
 * whole point (see the toolchain-upgrade plan row) -- those four migrations were written by
 * several agents across earlier waves, one of them shipped a no-op placeholder that had to be
 * caught and replaced by hand during integration, and nothing had ever run the chain end to end
 * against a real schema before this test. It is placed under `src/test`, not `src/androidTest`,
 * and run through Robolectric (`@RunWith(RobolectricTestRunner::class)`) rather than as a
 * `connectedAndroidTest` -- deliberately: the workstream's operating rules forbid `adb` and any
 * on-device/emulator step, and `./gradlew :app:testDebugUnitTest` (the task this project's CI
 * and this whole test suite already run through) is the only task that executes without one.
 * Robolectric ships a real native SQLite implementation for exactly this reason -- this is not a
 * mock, the migrations run against an actual `.db` file on disk in both directions.
 *
 * **What this test can and cannot honestly claim, and why.** [AppDatabase.exportSchema] was
 * `false` for this project's entire history until this same toolchain-upgrade pass turned it on
 * (see that class's doc) -- so there has never been a captured schema JSON for versions 8, 9, 10,
 * or 11 for [MigrationTestHelper]'s normal asset-backed `createDatabase(name, version)` to build
 * the starting database from. Only version 12 onward is exportable now, under
 * `app/schemas/au.com.threesixty.cabdispatch.data.local.AppDatabase/`.
 *
 * Rather than write a test that *looks* like it covers the chain but silently skips validating
 * the one step (the 8 -> 9 boundary) that has no exported schema to start from, this test builds
 * the v8 starting database BY HAND, with the exact `CREATE TABLE`/`CREATE INDEX` statements Room
 * would have generated for the entity classes as they stood at that version -- reconstructed by
 * reading those classes at the git commit that introduced [MIGRATION_8_9] (`4a68fcb`, the parent
 * of `e5af68e`), diffed against `HEAD` to confirm exactly what changed and nothing else did (see
 * each table's comment below for the diff that backs it). Everything from `runMigrationsAndValidate`
 * onward is real Room, validating the true annotation-derived v12 schema -- only the starting
 * point is hand-built rather than asset-built.
 *
 * `MigrationTestHelper.runMigrationsAndValidate` also loads the END version's schema from the
 * same assets convention (not just the start version), so the v12 JSON KSP now exports has to be
 * reachable from here too. It lives at `app/schemas/.../12.json` (source of truth, regenerated by
 * KSP on every build) with an identical copy checked in at `app/src/main/assets/.../12.json`
 * purely so Robolectric's `isIncludeAndroidResources` test-resource package (which only bundles
 * *main* sourceSet assets, not `src/test/assets`) can see it -- `src/test/assets` was tried first
 * and does not work for this. This does mean the schema JSON ships inside the real APK; it is a
 * public, non-secret description of the local SQLite table shapes, so that trade was taken
 * deliberately rather than fighting the Robolectric asset-loading path further. If a future
 * version bump adds `app/schemas/.../13.json`, copy it to the matching `main/assets` path too or
 * this test (and any later one added for the new version) will fail with the same
 * `FileNotFoundException` this one hit before that copy existed.
 *
 * That means: **every one of 8->9, 9->10, 10->11 and 11->12 genuinely executes and is genuinely
 * validated against Room's real compiled schema** for the *end* state of the chain. What is NOT
 * independently verified is that the hand-built v8 `CREATE TABLE` statements below are bit-for-bit
 * what a real v8 install actually had on disk -- there is no captured artifact from that version
 * to check them against, only the entity source at that commit. Getting a column name, type,
 * nullability or default wrong here would make [MigrationTestHelper.runMigrationsAndValidate]
 * fail LOUDLY (Room reports the exact expected-vs-found `TableInfo` diff) rather than silently
 * pass, so a wrong hand-built schema fails closed, not open -- but it is still hand-built, and
 * that is the one honest caveat on this test.
 */
@RunWith(RobolectricTestRunner::class)
// sdk = 34: Robolectric 4.13 has no API 35 SDK jar yet, and this app's targetSdk (35, per
// app/build.gradle.kts) is otherwise what Robolectric would pick by default -- purely a
// Robolectric/test-runner ceiling, unrelated to the migration logic under test itself.
// application = a plain android.app.Application, not the real CabDispatchApp: that class's
// onCreate() initialises the Mapbox SDK's native access-token setter
// (`MapboxOptions.setAccessToken`, CabDispatchApp.kt:26), which has no native library loaded
// under Robolectric and is completely unrelated to what this test is checking (Room migrations,
// not app startup). `isIncludeAndroidResources` (needed for the schema-JSON asset lookup below)
// otherwise pulls in the real merged manifest, including its real `android:name` Application
// class, so this has to be set explicitly.
@Config(manifest = Config.NONE, sdk = [34], application = android.app.Application::class)
class RoomMigrationTest {

    private val dbName = "migration-test.db"

    @get:Rule
    val helper: MigrationTestHelper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        AppDatabase::class.java,
    )

    /**
     * Builds a v8 database on disk with the schema [AppDatabase] had at that version -- see the
     * class doc above for how this was reconstructed and what that does and does not prove.
     * Uses a plain [FrameworkSQLiteOpenHelperFactory] (no Room involved yet) so nothing here
     * depends on the CURRENT `@Entity` classes; this is deliberately independent of them, the
     * same way a real device's on-disk v8 file would be.
     */
    private fun v8OpenHelper(context: android.content.Context): androidx.sqlite.db.SupportSQLiteOpenHelper {
        val configuration = androidx.sqlite.db.SupportSQLiteOpenHelper.Configuration.builder(context)
            .name(dbName)
            .callback(
                object : androidx.sqlite.db.SupportSQLiteOpenHelper.Callback(8) {
                    override fun onCreate(db: androidx.sqlite.db.SupportSQLiteDatabase) {
                        createV8Tables(db)
                    }

                    override fun onUpgrade(db: androidx.sqlite.db.SupportSQLiteDatabase, oldVersion: Int, newVersion: Int) {
                        // Not exercised -- MigrationTestHelper drives all upgrades itself via the
                        // real Migration objects, below.
                    }
                },
            )
            .build()
        return FrameworkSQLiteOpenHelperFactory().create(configuration)
    }

    private fun createV8Database() {
        val context = ApplicationProvider.getApplicationContext<android.content.Context>()
        context.deleteDatabase(dbName)
        // Force creation by opening once, then close -- reopened below to seed rows, and again
        // by MigrationTestHelper.runMigrationsAndValidate to actually run the migration chain.
        v8OpenHelper(context).writableDatabase.close()
    }

    /** Reopens the v8 file created by [createV8Database] to insert seed rows -- see the call
     * site's doc for why this, and not `MigrationTestHelper.createDatabase`, is used. */
    private fun openV8DatabaseForSeeding(): androidx.sqlite.db.SupportSQLiteDatabase {
        val context = ApplicationProvider.getApplicationContext<android.content.Context>()
        return v8OpenHelper(context).writableDatabase
    }

    /**
     * `trips`, `shifts`, `tariffs`, `tariff_signing_keys`, `sync_outbox` as they stood at v8 --
     * i.e. [AppDatabase]'s current entities MINUS every column/table added by [MIGRATION_8_9]
     * (`airportRankRequestedMaxi`), [MIGRATION_9_10] (`toll_roads`/`toll_gantries`/`toll_points`,
     * `simulated`, `autoTolledRoadsJson`, `unpricedTollRoadIdsJson`), [MIGRATION_10_11]
     * (`accruedDistanceCharge`/`accruedWaitingCharge`) and [MIGRATION_11_12]
     * (`nextAttemptAt`/`deadLettered`). `ShiftEntity`, `TariffEntity` and `TariffSigningKeyEntity`
     * are untouched between v8 and v12 (`git diff 4a68fcb HEAD -- .../ShiftEntity.kt
     * .../TariffEntity.kt .../TariffSigningKeyEntity.kt` is empty) so those three are transcribed
     * directly from the current entity classes.
     */
    private fun createV8Tables(db: androidx.sqlite.db.SupportSQLiteDatabase) {
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `trips` (
                `clientUuid` TEXT NOT NULL,
                `serverId` TEXT,
                `vehicleId` TEXT NOT NULL,
                `driverId` TEXT NOT NULL,
                `shiftId` TEXT,
                `tariffId` TEXT NOT NULL,
                `type` TEXT NOT NULL,
                `status` TEXT NOT NULL,
                `timeClass` TEXT NOT NULL,
                `isPeak` INTEGER NOT NULL,
                `maxi` INTEGER NOT NULL,
                `passengerCount` INTEGER NOT NULL DEFAULT 1,
                `wheelchairHiring` INTEGER NOT NULL DEFAULT 0,
                `startAt` TEXT NOT NULL,
                `endAt` TEXT,
                `startLat` REAL NOT NULL,
                `startLng` REAL NOT NULL,
                `endLat` REAL,
                `endLng` REAL,
                `distanceM` INTEGER NOT NULL DEFAULT 0,
                `movingS` INTEGER NOT NULL DEFAULT 0,
                `waitingS` INTEGER NOT NULL DEFAULT 0,
                `paymentMethod` TEXT NOT NULL DEFAULT 'cash',
                `tolls` TEXT NOT NULL DEFAULT '0',
                `extras` TEXT NOT NULL DEFAULT '0',
                `cleaningFee` TEXT NOT NULL DEFAULT '0',
                `surchargePct` TEXT,
                `includePsl` INTEGER NOT NULL DEFAULT 0,
                `receiptRef` TEXT,
                `voucherCode` TEXT,
                `accountReference` TEXT,
                `splitPaymentsJson` TEXT,
                `negotiatedTotal` TEXT,
                `tip` TEXT,
                `pickupAddress` TEXT,
                `dropoffAddress` TEXT,
                `deviceTotal` TEXT NOT NULL DEFAULT '0',
                `gpsTraceJson` TEXT NOT NULL DEFAULT '[]',
                `createdAt` INTEGER NOT NULL,
                `updatedAt` INTEGER NOT NULL,
                PRIMARY KEY(`clientUuid`)
            )
            """.trimIndent(),
        )
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `shifts` (
                `clientUuid` TEXT NOT NULL,
                `serverId` TEXT,
                `driverId` TEXT NOT NULL,
                `vehicleId` TEXT NOT NULL,
                `status` TEXT NOT NULL,
                `startAt` TEXT NOT NULL,
                `endAt` TEXT,
                `inspectionJson` TEXT,
                `tripsCount` INTEGER NOT NULL DEFAULT 0,
                `kmTotal` TEXT NOT NULL DEFAULT '0',
                `cashTotal` TEXT NOT NULL DEFAULT '0',
                `cardTotal` TEXT NOT NULL DEFAULT '0',
                `pslOwed` TEXT NOT NULL DEFAULT '0',
                `reconciled` INTEGER NOT NULL DEFAULT 0,
                `createdAt` INTEGER NOT NULL,
                `updatedAt` INTEGER NOT NULL,
                PRIMARY KEY(`clientUuid`)
            )
            """.trimIndent(),
        )
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `tariffs` (
                `id` TEXT NOT NULL,
                `region` TEXT NOT NULL,
                `effectiveFrom` TEXT NOT NULL,
                `effectiveTo` TEXT,
                `rawJson` TEXT NOT NULL,
                `fetchedAt` INTEGER NOT NULL,
                PRIMARY KEY(`id`)
            )
            """.trimIndent(),
        )
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `tariff_signing_keys` (
                `id` TEXT NOT NULL,
                `publicKeyBase64` TEXT NOT NULL,
                `algorithm` TEXT NOT NULL,
                `fetchedAt` INTEGER NOT NULL,
                PRIMARY KEY(`id`)
            )
            """.trimIndent(),
        )
        db.execSQL(
            """
            CREATE TABLE IF NOT EXISTS `sync_outbox` (
                `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                `entityType` TEXT NOT NULL,
                `clientUuid` TEXT NOT NULL,
                `entityJson` TEXT NOT NULL,
                `readyToSync` INTEGER NOT NULL,
                `createdAt` INTEGER NOT NULL,
                `attempts` INTEGER NOT NULL DEFAULT 0,
                `lastError` TEXT
            )
            """.trimIndent(),
        )
        db.execSQL(
            "CREATE UNIQUE INDEX IF NOT EXISTS `index_sync_outbox_entityType_clientUuid` " +
                "ON `sync_outbox` (`entityType`, `clientUuid`)",
        )
    }

    /**
     * The full chain in one go, plus a handful of rows carried through it -- proving not just
     * that the schema ends up right but that pre-existing data survives every step (the actual
     * risk a real driver's tablet runs: it always has trips already on disk when an upgrade
     * lands, per [AppDatabase]'s own "confirmed live, 2026-09-05" doc).
     */
    @Test
    fun migrate8To13_preservesDataAndEndsAtTheRealSchema() {
        createV8Database()
        // NOT `helper.createDatabase(dbName, 8)` -- that method resolves version 8's schema from
        // a bundled asset JSON ([MigrationTestHelper]'s normal, asset-backed path), which does
        // not exist for this version (see the class doc above). Re-open the same hand-built file
        // directly instead, through the same plain [FrameworkSQLiteOpenHelperFactory] used to
        // create it, purely to seed a couple of rows before the real migration run below.
        openV8DatabaseForSeeding().apply {
            execSQL(
                """
                INSERT INTO trips (
                    clientUuid, vehicleId, driverId, shiftId, tariffId, type, status, timeClass,
                    isPeak, maxi, startAt, startLat, startLng, createdAt, updatedAt
                ) VALUES (
                    'trip-1', 'veh-1', 'drv-1', NULL, 'tariff-1', 'rank_hail', 'closed', 'day',
                    0, 0, '2026-09-01T00:00:00Z', -33.8, 151.2, 1000, 2000
                )
                """.trimIndent(),
            )
            execSQL(
                "INSERT INTO sync_outbox (entityType, clientUuid, entityJson, readyToSync, createdAt) " +
                    "VALUES ('trip', 'trip-1', '{}', 1, 1000)",
            )
            close()
        }

        // Run the real migrations, in order, and validate the result against Room's own
        // compiled expectation for v12 -- this is where a wrong hand-built v8 schema OR a wrong
        // migration (e.g. the no-op placeholder the plan calls out) would fail loudly.
        // 13, not 12: MIGRATION_12_13 (airport zones + trips.airportAccessFeeJson) joins the
        // chain, and its end-state schema is app/schemas/.../13.json, copied to main/assets per
        // this class's doc.
        helper.runMigrationsAndValidate(
            dbName,
            13,
            true,
            MIGRATION_8_9,
            MIGRATION_9_10,
            MIGRATION_10_11,
            MIGRATION_11_12,
            MIGRATION_12_13,
        )

        // Re-open through the real Room database (not the raw helper) so Room's own onOpen
        // schema validation runs too against the migrated file -- this is a second, independent
        // check beyond runMigrationsAndValidate above, exercised through the exact
        // Room.databaseBuilder(...).build() call [au.com.threesixty.cabdispatch.data.AppContainer]
        // makes in production. Verification below reads raw SQL (SupportSQLiteDatabase), not the
        // DAOs -- deliberately: this test's job is to prove the SCHEMA migration is real and
        // data-preserving, not to exercise DAO query logic, so it does not need to add any new
        // method to a production DAO interface.
        val context = ApplicationProvider.getApplicationContext<android.content.Context>()
        val db = Room.databaseBuilder(context, AppDatabase::class.java, dbName)
            // MIGRATION_13_14 (live map redesign, 2026-09-09) added so this real Room open —
            // which always targets AppDatabase's compiled CURRENT version, 14 now — can complete
            // the 13->14 step too; runMigrationsAndValidate above deliberately still stops at 13
            // (the last version with an exported/asset-copied schema JSON this test hand-verifies
            // against), so the raw file handed to this builder is genuinely at 13 and needs this
            // one extra step, exactly mirroring AppContainer's own migrations list.
            .addMigrations(MIGRATION_8_9, MIGRATION_9_10, MIGRATION_10_11, MIGRATION_11_12, MIGRATION_12_13, MIGRATION_13_14)
            .build()
        try {
            val raw = db.openHelper.readableDatabase
            raw.query("SELECT * FROM trips WHERE clientUuid = 'trip-1'").use { c ->
                check(c.moveToFirst()) { "trip-1 did not survive the 8->9->10->11->12 migration chain" }
                // Old data, new columns: every column added along the way must have landed on
                // the pre-existing row at its migration's documented default, not null/crash.
                check(c.getInt(c.getColumnIndexOrThrow("airportRankRequestedMaxi")) == 0) {
                    "MIGRATION_8_9 default wrong (airportRankRequestedMaxi)"
                }
                check(c.getInt(c.getColumnIndexOrThrow("simulated")) == 0) {
                    "MIGRATION_9_10 default wrong (simulated)"
                }
                check(c.getString(c.getColumnIndexOrThrow("autoTolledRoadsJson")) == "{}") {
                    "MIGRATION_9_10 default wrong (autoTolledRoadsJson)"
                }
                check(c.getString(c.getColumnIndexOrThrow("unpricedTollRoadIdsJson")) == "[]") {
                    "MIGRATION_9_10 default wrong (unpricedTollRoadIdsJson)"
                }
                check(c.getString(c.getColumnIndexOrThrow("accruedDistanceCharge")) == "0") {
                    "MIGRATION_10_11 default wrong (accruedDistanceCharge)"
                }
                check(c.getString(c.getColumnIndexOrThrow("accruedWaitingCharge")) == "0") {
                    "MIGRATION_10_11 default wrong (accruedWaitingCharge)"
                }
                // MIGRATION_12_13: nullable, no default -- an old trip honestly has no airport
                // fee record, rather than a fabricated one.
                check(c.isNull(c.getColumnIndexOrThrow("airportAccessFeeJson"))) {
                    "MIGRATION_12_13 default wrong (airportAccessFeeJson should be NULL)"
                }
            }

            // The airport-zone cache table from MIGRATION_12_13 exists and starts empty (the
            // fare engine's compiled-fallback state -- see AirportZoneCache's doc).
            raw.query("SELECT COUNT(*) FROM airport_zones").use { c ->
                check(c.moveToFirst() && c.getInt(0) == 0) {
                    "airport_zones should start empty after a migration, not seeded"
                }
            }

            // The new toll-registry tables from MIGRATION_9_10 exist and are queryable (empty is
            // correct -- see that migration's own "offline-empty-cache is a safe state" doc).
            raw.query("SELECT COUNT(*) FROM toll_roads").use { c ->
                check(c.moveToFirst() && c.getInt(0) == 0) {
                    "toll_roads should start empty after a migration, not seeded"
                }
            }

            // sync_outbox's row survived, with MIGRATION_11_12's new columns at their documented
            // "existing rows are unaffected" defaults.
            raw.query("SELECT * FROM sync_outbox WHERE clientUuid = 'trip-1'").use { c ->
                check(c.moveToFirst()) { "sync_outbox row did not survive the migration chain" }
                check(c.getLong(c.getColumnIndexOrThrow("nextAttemptAt")) == 0L) {
                    "MIGRATION_11_12 default wrong (nextAttemptAt)"
                }
                check(c.getInt(c.getColumnIndexOrThrow("deadLettered")) == 0) {
                    "MIGRATION_11_12 default wrong (deadLettered)"
                }
            }
        } finally {
            db.close()
        }
    }
}
